spring:
  application:
    name: powstash
    allowed-origin: ${JAVA_FRONTEND_URL:http://localhost:3000}
  datasource:
    url: ${JAVA_POWSTASH_URL}
    username: ${JAVA_USER}
    password: ${JAVA_MYSQL_PASSWORD}
  jpa:
    show-sql: true